apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluentd-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      containers:
        - name: fluentd
          image: akiyamko423/fluentd:1.0
          env: 
            - name: FLUENT_TCP_PORT
              value: "5170"
          volumeMounts:
            - name: config-path
              mountPath: /fluentd/etc
      volumes:
        - name: config-source
          configMap:
            name: fluent-conf-configmap
        - name: config-path
          emptyDir: {}
      initContainers:
        - name: config-fluentd
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh","-c"]
          args:
          - cp /fluentd/etc2/fluent.conf /fluentd/etc/fluent.conf;
          volumeMounts:
            - name: config-path
              mountPath: /fluentd/etc
            - name: config-source
              mountPath: /fluentd/etc2
---
apiVersion: v1
kind: Service
metadata:
  name: fluentd-svc
  labels:
    app: fluentd
spec:
  type: NodePort
  ports:
  - port: 5160
    targetPort: 5170
    protocol: TCP
    name: http
    nodePort: 30080
  selector:
    app: fluentd